// Package render defines the frontend seam — the boundary between the SSH
// session controller and however pixels (or terminal cells) get on screen.
//
// A Frontend reads remote output from a Controller, feeds it into a
// terminal.Engine, presents the resulting grid, and forwards user input back to
// the Controller. The default build uses the stdio passthrough frontend; the
// Ebitengine GPU frontend lives behind the `ebiten` build tag. The headless
// frontend here is renderer-free and exists so the full pipeline can be tested.
package render

import (
	"context"
	"io"

	"github.com/billzhuang/wisp/internal/terminal"
)

// Controller is the subset of *app.Controller a frontend needs. Keeping it an
// interface (rather than importing app) avoids an import cycle and makes
// frontends trivially testable with a fake.
type Controller interface {
	// Stdout is the remote output stream to feed into the terminal engine.
	Stdout() io.Reader
	// Input forwards locally-generated bytes to the remote stdin.
	Input(p []byte) error
	// Resize informs the remote PTY of a new window size.
	Resize(cols, rows int) error
}

// Frontend drives the user interface until the session ends or ctx is
// cancelled.
type Frontend interface {
	Run(ctx context.Context, ctrl Controller, eng terminal.Engine) error
}

// UpdatePrompter is an optional capability: a frontend that can surface an
// in-app "update available, click to install" prompt (the Ghostty-style
// affordance). The GUI frontend implements it; the stdio frontend does not, so
// callers must type-assert. install is invoked when the user accepts; it
// downloads, verifies and replaces the binary, and returns any error to show.
type UpdatePrompter interface {
	SetUpdate(notice string, install func() error)
}

// TabInfo is one entry in a frontend's tab strip.
type TabInfo struct {
	Title  string // short label, e.g. "#1"
	Active bool   // whether this is the selected tab
}

// TabController is the optional multi-session capability a frontend can drive.
// A frontend obtains it by type-asserting the render.Controller it is given: the
// controller owns N concurrent sessions ("tabs"), pumps each session's output
// into its own terminal.Engine (so background tabs stay live), and routes
// Input/Resize to the active one. *app.Tabs is the production implementation;
// the stdio/headless frontends never see it. The embedded Controller's Stdout is
// unused in tab mode — the per-tab pumps own the real output streams — so the
// frontend renders via ActiveEngine instead.
type TabController interface {
	Controller

	// ActiveEngine is the engine of the currently selected tab: the grid the
	// frontend draws each frame.
	ActiveEngine() terminal.Engine

	// ActiveLoading reports whether the active tab is still waiting for its
	// first byte of remote output, so the frontend can show a connecting splash.
	ActiveLoading() bool

	// TabList lists every open tab in display order, for the tab strip.
	TabList() []TabInfo

	// NewTab opens an additional session and switches to it. It may block while
	// the new session is dialed, so callers should invoke it off the UI loop.
	NewTab() error

	// CloseActiveTab closes the active session and selects an adjacent one. It
	// is a no-op when only one tab remains (there is always at least one).
	CloseActiveTab()

	// NextTab and PrevTab move the selection, wrapping at the ends.
	NextTab()
	PrevTab()
}

// TabCapable marks a Frontend that can present a TabController as tabs. main
// builds a multi-session controller only for such frontends; the rest receive a
// single-session controller and never exercise the tab methods.
type TabCapable interface {
	SupportsTabs() bool
}

// Headless is a renderer-free Frontend: it pumps remote output into the engine
// and blocks until the stream ends or ctx is cancelled. It draws nothing, which
// makes it ideal for tests and for validating the network→engine seam (Phase 1
// / Phase 3) without a display.
type Headless struct {
	// OnFrame, if set, is called after each chunk of remote output is applied
	// to the engine. Tests use it to observe the grid as it fills in.
	OnFrame func(terminal.Engine)
}

// Run implements Frontend.
func (h Headless) Run(ctx context.Context, ctrl Controller, eng terminal.Engine) error {
	done := make(chan error, 1)
	go func() {
		buf := make([]byte, 32*1024)
		r := ctrl.Stdout()
		for {
			n, err := r.Read(buf)
			if n > 0 {
				if _, werr := eng.Write(buf[:n]); werr != nil {
					done <- werr
					return
				}
				if h.OnFrame != nil {
					h.OnFrame(eng)
				}
			}
			if err != nil {
				if err == io.EOF {
					done <- nil
				} else {
					done <- err
				}
				return
			}
		}
	}()

	select {
	case <-ctx.Done():
		return ctx.Err()
	case err := <-done:
		return err
	}
}
