// Package render defines the frontend seam — the boundary between the SSH
// session controller and however pixels (or terminal cells) get on screen.
//
// A Frontend reads remote output from a Controller, feeds it into a
// terminal.Engine, presents the resulting grid, and forwards user input back to
// the Controller. The default build uses the stdio passthrough frontend; the
// Ebitengine GPU frontend lives behind the `ebiten` build tag. The headless
// frontend here is renderer-free and exists so the full pipeline can be tested.
package render

import (
	"context"
	"io"

	"github.com/billzhuang/wisp/internal/terminal"
)

// Controller is the subset of *app.Controller a frontend needs. Keeping it an
// interface (rather than importing app) avoids an import cycle and makes
// frontends trivially testable with a fake.
type Controller interface {
	// Stdout is the remote output stream to feed into the terminal engine.
	Stdout() io.Reader
	// Input forwards locally-generated bytes to the remote stdin.
	Input(p []byte) error
	// Resize informs the remote PTY of a new window size.
	Resize(cols, rows int) error
}

// Frontend drives the user interface until the session ends or ctx is
// cancelled.
type Frontend interface {
	Run(ctx context.Context, ctrl Controller, eng terminal.Engine) error
}

// Headless is a renderer-free Frontend: it pumps remote output into the engine
// and blocks until the stream ends or ctx is cancelled. It draws nothing, which
// makes it ideal for tests and for validating the network→engine seam (Phase 1
// / Phase 3) without a display.
type Headless struct {
	// OnFrame, if set, is called after each chunk of remote output is applied
	// to the engine. Tests use it to observe the grid as it fills in.
	OnFrame func(terminal.Engine)
}

// Run implements Frontend.
func (h Headless) Run(ctx context.Context, ctrl Controller, eng terminal.Engine) error {
	done := make(chan error, 1)
	go func() {
		buf := make([]byte, 32*1024)
		r := ctrl.Stdout()
		for {
			n, err := r.Read(buf)
			if n > 0 {
				eng.Write(buf[:n])
				if h.OnFrame != nil {
					h.OnFrame(eng)
				}
			}
			if err != nil {
				if err == io.EOF {
					done <- nil
				} else {
					done <- err
				}
				return
			}
		}
	}()

	select {
	case <-ctx.Done():
		return ctx.Err()
	case err := <-done:
		return err
	}
}
